[project]
name = "Dotacovatko"
version = "1.0.0"
description = "A tool to help create tables for the ministry of internal affairs of the Czech Republic"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "annotated-types==0.8.0",
    "certifi==2026.7.22",
    "charset-normalizer==3.4.9",
    "customtkinter==6.0.0",
    "darkdetect==0.8.0",
    "et-xmlfile==2.0.0",
    "idna==3.18",
    "librt==0.15.0",
    "mypy==2.3.0",
    "mypy-extensions==1.1.0",
    "numpy==2.5.2",
    "openpyxl==3.1.5",
    "packaging==26.3",
    "pandas==3.0.5",
    "pandas-stubs>=3.0.5.260730",
    "pathspec==1.1.1",
    "pydantic==2.13.4",
    "pydantic-core==2.46.4",
    "python-dateutil==2.9.0.post0",
    "pywin32==312",
    "requests==2.34.2",
    "ruff==0.16.2",
    "six==1.17.0",
    "tk==0.1.0",
    "typing-extensions==4.16.0",
    "typing-inspection==0.4.3",
    "tzdata==2026.3",
    "urllib3==2.7.0",
    "xlwings==0.36.14",
]

[dependency-groups]
dev = [
]

[tool.mypy]
python_version = "3.14"
strict = true
pretty = true
show_error_context = true
show_column_numbers = true
show_error_codes = true
explicit_package_bases = true
mypy_path = "src"
plugins = [
    "pydantic.mypy"
]

[tool.ruff]
src = ["src"]
line-length = 120
target-version = "py314"
show-fixes = true
output-format = "full"

[tool.ruff.lint]
select = [
    "ALL"
]

ignore = [
    "S101",
    "RUF003"
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
docstring-code-line-length = 120
