"""Contains the headers for the datafreame containing parsed employee data."""

from enum import StrEnum


class EmployeeDataHeaders(StrEnum):
    """Enum containing the headers for the datafreame containing parsed employee data."""

    SURNAME = "SURNAME"
    FIRST_NAME = "FIRST_NAME"
    BIRTH_NUM = "BIRTH_NUM"
    CONTRACT_START_DATE = "CONTRACT_START_DATE"
    CONTRACT_END_DATE = "CONTRACT_END_DATE"
    INSURANCE_CODE = "INSURANCE_CODE"
    DISABILITY_RECOGNISED_FROM = "DISABILITY_RECOGNISED_FROM"
    DISABILITY_RECOGNISED_TO = "DISABILITY_RECOGNISED_TO"
    DISABILITY_STATUS = "DISABILITY_STATUS"
    GROSS_PAY_FIRST_MONTH = "GROSS_PAY_FIRST_MONTH"
    GROSS_PAY_SECOND_MONTH = "GROSS_PAY_SECOND_MONTH"
    GROSS_PAY_THIRD_MONTH = "GROSS_PAY_THIRD_MONTH"
    PAY_FOR_ACTUAL_WORK_FIRST_MONTH = "PAY_FOR_ACTUAL_WORK_FIRST_MONTH"
    PAY_FOR_ACTUAL_WORK_SECOND_MONTH = "PAY_FOR_ACTUAL_WORK_SECOND_MONTH"
    PAY_FOR_ACTUAL_WORK_THIRD_MONTH = "PAY_FOR_ACTUAL_WORK_THIRD_MONTH"
    INSURANCE_PAYMENT_FIRST_MONTH = "INSURANCE_PAYMENT_FIRST_MONTH"
    INSURANCE_PAYMENT_SECOND_MONTH = "INSURANCE_PAYMENT_SECOND_MONTH"
    INSURANCE_PAYMENT_THIRD_MONTH = "INSURANCE_PAYMENT_THIRD_MONTH"
